export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAIL = 'CHECK_AUTH_FAIL';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';


export const CART_SUCCES = 'CART_SUCCES';
export const CART_FAIL = 'CART_FAIL';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART';
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';
export const RM_ITEM_FROM_CART_SUCCESS = 'RM_ITEM_FROM_CART_SUCCESS';
export const RM_ITEM_FROM_CART_FAIL = 'RM_ITEM_FROM_CART_FAIL';
export const DEC_ITEM_FROM_CART_SUCCES = 'DEC_ITEM_FROM_CART_SUCCES';
export const DEC_ITEM_FROM_CART_FAIL = 'DEC_ITEM_FROM_CART_FAIL';